### ISSUE TITLE
How is it working?

### ISSUE THREAD

**Issue by MysteryIII** [Rawi01/XposedUnifiedNlp#1]
Hi,
I'm just a curious about how is it working:
is it an addition to Google's locating method, making it more accurate and/or faster?
Or is it a replacement? If so, is it "just" about privacy (Google not getting your location data) or is it better then Google's location service?
What are the advantages and disadvantages?

**Comment by Rawi01** [comment]
UnifiedNlp is a replacement for the network location service provided by Google. 

There are several backends that use different sources to determine your location.
For example you can install the <a href="https://github.com/microg/AppleWifiNlpBackend">AppleWifiNlpBackend</a> which uses Apple's service. One big advantage of this backend is that the location of the access points are saved on your device which reduce the amount of requests to the servers which leads to better privacy, reduced data usage and increased performance.

A list of available backends and some more information could be found at the <a href="https://github.com/microg/android_packages_apps_UnifiedNlp">UnifiedNlp project page</a>.

The reason for this module is that it is not possible to use it with a system where GAPPS are installed.

**Comment by MysteryIII** [comment]
Thanks for the information! I will give it a try.

**Comment by ntzb** [comment]
Hi.
how do you know which location services are used?
if you have both installed, how do you know the unifiedNLP one will be used?

**Comment by Rawi01** [comment]
The same question was discussed at microg/android_packages_apps_UnifiedNlp#20

The easiest way is to disable gps and then try to get the network location with an app like <a href="https://f-droid.org/repository/browse/?fdfilter=location&fdid=com.borneq.heregpslocation">Here GPS Location</a>. After you get a location, disable all backends. If it gets no location, you know that UnifiedNLP is active.

Another way is to have a look at the android logs.

**Comment by bungabunga** [comment]
so, with this module (+unifiednlp +backend) i have another location service installed on my phone. how do i set my phone to not use google service but use this one instead?

**Comment by Rawi01** [comment]
If you use this module you not longer use the Google network location module. It is a replacement.

**Comment by bungabunga** [comment]
great! that's what i wanted. thanks.
