### ISSUE TITLE
Address lookup not redirected to UnifiedNlp

### ISSUE THREAD

**Issue by kailiu42** [Rawi01/XposedUnifiedNlp#3]
First of all I'd like to say thanks. I've installed this module and confirmed that the location lookup is working correctly. However address lookup still goes to Google instead of goes to the backend I set in UnifiedNlp settings, currently the only available one called NominatimGeocoderBackend.

I can confirm NominatimGeocoderBackend itself is working. If I remove Google Play Service and install the NetworkLocation.apk, the address lookup works without any issue. As Google and NominatimGeocoderBackend returns different description of my location I can easily tell the address is provided by which of them. With this xposed module installed, the address returned is still Google's.

I'm not an Android developer but after doing some homework it seems that your module only changed config_networkLocationProviderPackageName but not config_geocoderProviderPackageName so that it still goes to Google by default. Could you fix this? Thanks in advance.

**Comment by Rawi01** [comment]
You are totally right, I will add it today.

**Comment by kailiu42** [comment]
Downloaded latest 1.0.3 version and geocoder works OK now. Thanks.
