### ISSUE TITLE
XposedUnifiedNlp on Lollipop and Marshmallow

### ISSUE THREAD

**Issue by bungabunga** [Rawi01/XposedUnifiedNlp#4]
hey there! i've been using XposedUnifiedNlp on Kitkat with great pleasure. but when i updated my phone (Xperia Z3C) to Lollipop 5.1 it caused heavy boot loops.

do you know if your module works on Lollipop 5.1 (maybe i did something wrong) and if not are you planing to upgrade it?

best,

jure

**Comment by xuefer** [comment]
what about new xposed framework?

**Comment by IzzySoft** [comment]
I'm using this module on Lollipop (5.1.1), no boot-loops – so I second what xuefer suggests: did you update the framework accordingly?

Apart from that: the module itself as well as UnifiedNLP tell me they don't get any location. Still, apps display the location correctly. Which leads me to the question who's providing it. Does the module still work as it should on Lollipop – or does my device use Google Location despite of the module being installed? For details, please see [this issue at the UnifiedNLP project](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/92).

**Comment by bungabunga** [comment]
thanks! to bad i just upgraded my device to MM, so the question for me now is: is it working on MM?

for me it worked perfectly on KK, but when i got to LP i got bootloops (yes i updated framework the right way). they were maybe not the module's fault but i went through factory reset device hell so many times that i just couldn't go once more.

an advice for you: maybe you should freeze google location provider with Titanium Backup, just to see where are you getting your locations from. If it's freezed then it couldn't get from anywhere else then UnifiedNLP.

**Comment by IzzySoft** [comment]
@bungabunga 

> maybe you should freeze google location provider with Titanium Backup, just to see where are you getting your locations from. If it's freezed then it couldn't get from anywhere else then UnifiedNLP.

Good point, thanks!

> is it working on MM?

There's already an issue for that you might wish to add your +1 and subscribe to: [please add support for android 6](https://github.com/Rawi01/XposedUnifiedNlp/issues/5)

**Comment by Rawi01** [comment]
Unfortunately my current device only supports android 4.4.4. I have some free time tomorrow and will try to use the emulator to test and fix it on Lollipop and Marshmallow.

**Comment by Rawi01** [comment]
Just added a new version([1.0.4-EXPERIMENTAL](http://repo.xposed.info/module/de.r3w6.xposedunifiednlp)). It works on Lollipop(5.0/5.1) and Marshmallow(no real device test, emulator only). Would be great if someone could test it and give some feedback. 

I also added a DummyBackend that always returns the same location(42,42) which could be used for testing. 

The UnifiedNlp self check seems to be broken([#72](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/72), [#76](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/76), [#88](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/88), [#92](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/92)) but the XposedUnifiedNlp check should work.

**Comment by IzzySoft** [comment]
Thanks for the fast work, @Rawi01 ! I've just updated the module. Looks like a success: "Check Settings" reports "Everything seems to be fine" :thumbsup: Quick check with an app using location: Works perfectly! If you can tell me what to look for in logcat for a final confirmation that the location indeed comes from UnifiedNLP and not Google, I'd look that up as well.

**Comment by IzzySoft** [comment]
Yay! Look what I found in the logs this morning:

<pre>
V/NlpLocationBackendFuser(  799): location=Location[network 48,167156,11,572620 acc=500 et=+11h45m5s647ms {Bundle[{noGPSLocation=Location[network 48,167156,11,572620 acc=500 et=+11h45m5s647ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
V/NlpLocationBackendFuser(  799): location=Location[network 48,167156,11,572620 acc=500 et=+11h45m5s836ms {Bundle[{noGPSLocation=Location[network 48,167156,11,572620 acc=500 et=+11h45m5s836ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
V/NlpLocationProvider(  799): onSetRequest: ProviderRequest[ON interval=+24h0m0s0ms] by WorkSource{1000 android}
V/NlpLocationProvider(  799): using autoUpdate=true autoTime=86400000
V/NlpLocationBackendFuser(  799): location=Location[network 48,167156,11,572620 acc=500 et=+11h45m17s370ms {Bundle[{noGPSLocation=Location[network 48,167156,11,572620 acc=500 et=+11h45m17s370ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
V/NlpLocationBackendFuser(  799): location=Location[network 48,167156,11,572620 acc=500 et=+11h45m21s361ms {Bundle[{noGPSLocation=Location[network 48,167156,11,572620 acc=500 et=+11h45m21s361ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]
</pre>

Looks good I'd say :+1:

**Comment by bungabunga** [comment]
1.0.4.-EXPERIMENTAL installs good on Marshmallow (no bootloops), self test also shows it is working and it gets mentioned at Android Menu/Location/Location services.

however, a map app that i use (Maps.me) only works until i freeze Google Play Services, then it can't get the location. also, UnifiedNlp/settings/self check it says there's no last known location (everything else is good) as somebody mentioned. so i can't say that it's really working.

**Comment by IzzySoft** [comment]
@bungabunga looking at logcat might help there. There are several apps out there simply refusing to work if they don't find the "official" Google services – no idea what they're looking at. I have several devices without GApps, and experienced this now and then: "You cannot use location as this requires Google Services, which are not installed on your device". True they are not, but other apps have no issues getting the location via microG/UnifiedNLP.

So that might well be a bug in that specific app which, not finding GServices, doesn't even try obtaining the location. Wouldn't be the first or the only one. Have you tried the location with other apps? Do they all fail, or is it just Maps.me? Maybe worth trying: [FakeGApps](http://repo.xposed.info/module/com.thermatk.android.xf.fakegapps).

**Comment by bungabunga** [comment]
@IzzySoft thanks for your reply. could you name some app that should work with UnifiedNlp?

FakeGapps is not an option. it requires GmsCore, which is not supported by my (stock) rom. also, it's too alpha for me right now.

**Comment by IzzySoft** [comment]
Sure. Try [MobilityMap](https://play.google.com/store/apps/details?id=de.mymobilitymap.android). Works on my Google-less devices :)

**Comment by bungabunga** [comment]
@Rawi01 I observed the logs and can confirm that XposedUnifiedNlp+UnifiedNlp work on Marshmallow, even with Maps.Me. Yay! :)
(i did some mistakes on previous testings)

@IzzySoft funny, MobilityMap was the only app that didn't work, it poped up notification and demanded Google PLay Services. Maybe you have a different non-PlayStore build?

so i am closing this issue.. :)

**Comment by IzzySoft** [comment]
@bungabunga No idea what that could be. Or rather, I have an idea: You've just made GServices invisible, while I've replaced them by microG so the app might _think_ GServices are there. But nevermind: Main thing is it works, and the issue is fixed :) So once more, thanks to @Rawi01 !

**Comment by IzzySoft** [comment]
1.0.4.-EXPERIMENTAL crashes for me on MM (just had to setup a new, or rather freshly repaired device). And now I seem to have the same issue as reported by @bungabunga :

> UnifiedNlp/settings/self check it says there's no last known location

And as said, self-check in XposedUnifiedNlp makes itself crash.
