### ISSUE TITLE
Support for Android 7

### ISSUE THREAD

**Issue by breversa** [Rawi01/XposedUnifiedNlp#6]
Now that Xposed is available for Android 7 Nougat, I tried to use XposedUnifieldNlp along with μg UnifiedNlp (GAPPS), to no avail :

When doing the self-check in UnifiedNlp settings, the "UnifiedNlp is registered in system" checkbox remains unchecked.

**Comment by andrewreds** [comment]
I was running into a similar issue (Trying to get UnifiedNlp to run) and getting everything set but the "UnifiedNlp is registered in system" checkbox).

I was able to get things working by sideloading the apk as a system app.:

Remove existing UnifiedNlp package from phone

On Computer with adb access to the phone:

Download UnifiedNlp.apk from https://github.com/microg/android_packages_apps_UnifiedNlp/releases

Run:

```
adb root
adb remount
adb push UnifiedNlp.apk /system/priv-app/UnifiedNlp.apk
adb reboot
```
You will have to re-enable the backends.

Hope this Helps.

**Comment by Silverstar** [comment]
I am on Android 7.1 MIUI 9.2 and try to get this working as well, but have the same error as OP, even with unifiednlp apk in priv-app. I tried it with Resurrection Remix as well, but no way. 
Is Nougat so special so the module needs an update?
Any suggestions?

**Comment by Silverstar** [comment]
I am facing the same issue on Android 7.1 (Xiaomi.eu MIUI 9.2 as well as on RR).
Apk in priv-app and module enabled, but no success. 
May the module need an update?
UnifiedNLP is shown in settings, but trying to switch it on just opens it, self check shows "not registered" and after going back, switch is again in off state. 
I even tried the UnifiedNLP with gapps patcher from XDA, which should patch the framework-res.apk to include microg.nlp as a location provider,, but then my device doesn't boot. 
I am not familiar with Android programming nor Xposed, but I had a look in this source and shouldn't the code check/replace microg.nlp instead microg.gms?

**Comment by helllamer** [comment]
@andrewreds Thanks, working perfectly on latest LineageOS snapshot. The only change was: for NO-gapps one should download and use `NetworkLocation.apk`, not `UnifiedNlp.apk`.

**Comment by breversa** [comment]
@andrewreds :
Sorry for the very late answer, but your solution works !
I actually wrote a quick bash script (for KDE, mind you) that people might find useful :

```
#!/bin/bash

usage="${0} [gapps|nogapps]"

if [ ${#} -lt 1 ]; then
	echo ${usage}
	exit 1
fi


case $1 in
"gapps")
	apk="UnifiedNlp.apk"

;;
"nogapps")
	apk="NetworkLocation.apk"

;;
*)
	echo ${usage}
	exit 1
;;
esac

kdesudo -t -c "adb root && adb remount && adb push ${apk} /system/priv-app/NetworkLocation.apk"
wait
```
As you can see, it intalls the right apk file (found in  the same directory as the script) whether you're using gapps or nogapps.
