### ISSUE TITLE
Let dummy backend set coordinates?

### ISSUE THREAD

**Issue by ninep9up** [Rawi01/XposedUnifiedNlp#7]
Hey. I've been thinking if you could add an option of setting precise dummy coordinates to your yet built-in backend, suppose I want to use geoblocked apps and stuff?

I want to use your xposed module just for that, though I don't have a separate UnifiedNlp, but core detects it.

**Comment by ninep9up** [comment]
Can I bump it for the sake of humanity?

**Comment by Rawi01** [comment]
Hi, writing a backend that provides custom locations should be quite easy but is clearly not part of this project. Have you tried to search for an implementation that supports custom fake locations?

**Comment by ninep9up** [comment]
> 
> 
> Hi, writing a backend that provides custom locations should be quite easy but is clearly not part of this project. Have you tried to search for an implementation that supports custom fake locations?

I have.

**Comment by ninep9up** [comment]
I've also tried some Xposed modules, as well as apps, but they are nor as low-level and neither gsf-optimized requiring original frameworks and not the custom nlp core.

**Comment by ninep9up** [comment]
I wouldn't bump this if I had any success. I sort of try to make a beast out of my 2013 tablet which runs 4.1.2. This requires elegant solutions most of the time, and your backend is one of them.

**Comment by ninep9up** [comment]
I try to bump every issue that has potential to be resolved and be of use aftwerwards. There are guys that still wouldn't add a resolution for hover extensions when showing subtitles in-browser for almost a month now, for example. It kinda bums when we as humanity are responsible for these strange hiatuses.

**Comment by ninep9up** [comment]
This would change the acquisition of the information tenfolds, more, some are just critical in acquiring bits. Stuff that's geolocked nowadays is just out of order with the global human self-conscious, I try to fix this with your help.

**Comment by ninep9up** [comment]
OK, please just say that everyone is a bot here and I live in a matrix waiting for things that are extremely unbounded to its inner structure.

**Comment by mirfatif** [comment]
@ninep9up I think you are unnecessarily getting it on your nerves. The people here who are contributing to free and open source projects do a favor to the community and we must be grateful to them. You can request a feature or report a bug but it's not an obligation on the developer to fulfill your requirement immediately. They might have limitations; technical or others. They could possibly be going through hard times, or might be working on some other project which is more beneficial to more people.

So if the developer thinks that the feature you requested (which I think is a good one) isn't worth considering at the moment you shouldn't force them. Or if it's of the utmost importance to you, you can get it done as a paid project.
I hope you understand 🙂

**Comment by ninep9up** [comment]
> 
> 
> @ninep9up I think you are unnecessarily getting it on your nerves. The people here who are contributing to free and open source projects do a favor to the community and we must be grateful to them. You can request a feature or report a bug but it's not an obligation on the developer to fulfill your requirement immediately. They might have limitations; technical or others. They could possibly be going through hard times, or might be working on some other project which is more beneficial to more people.
> 
> So if the developer thinks that the feature you requested (which I think is a good one) isn't worth considering at the moment you shouldn't force them. Or if it's of the utmost importance to you, you can get it done as a paid project.
> I hope you understand 🙂

If one can't think he's into it anymore, should just reply with 'whatever, do it yourself'. Taking a month to get an opinion on the subject, that's too unproductive **for everyone**. I wouldn't think everyone's Urasawa Naoki's here, but getting two lines of code if you're familiar with a subject is three minutes of time. Month of silence is 14400 times that.

**Comment by ninep9up** [comment]
I'm not familiar with Android development, I consider myself an artist, but one can easily see one needs to set an option and ui for setting coordinates here: https://github.com/Rawi01/XposedUnifiedNlp/blob/master/app/src/main/java/de/r3w6/xposedunifiednlp/DummyBackend.java

**Comment by ninep9up** [comment]
Searching tells that this is called a dialogue box and can be configured based on this: https://developer.android.com/guide/topics/ui/dialogs#java

**Comment by ninep9up** [comment]
While needed examples can be found within these: https://stackoverflow.com/questions/10903754/input-text-dialog-android

**Comment by ninep9up** [comment]
Though I'd prefer something of this sort, possibly. https://stackoverflow.com/questions/24977051/android-custom-dialog-with-number-scrollable-picker

**Comment by ninep9up** [comment]
I'm rest assured the one who's created this well knows of everything that is mentioned here, that's why I feel like an idiot here.

**Comment by ninep9up** [comment]
Whatever, I can live with this, the moment the world begins to tell me everything's fake and we begin to drink cider which comes from nowhere.

**Comment by ninep9up** [comment]
I know of buddhism and dukkha, but getting your eyes set on something not very genuine to believe is some sort of a thing even buddhism struggles to acknowledge as a phenomenon.

**Comment by ninep9up** [comment]
I'm too idealistic, I should've smoked more and get out of the window while the depression peaked, not to have hoped the fractured machine of existence has some sort of collective conscience.

**Comment by ninep9up** [comment]
Being an artist was a mistake, not in a province with the people with a mind of a worm.

**Comment by ninep9up** [comment]
I thought programmers are the beings, one who struggle to be atop, to form new rules. I guess, I was wrong. This is fashion, nothing more.

**Comment by ninep9up** [comment]
A dogmatic one, at that.

**Comment by ninep9up** [comment]
If I ever get to the other side I wanna be this guy who simulates this consistent not-ableness, must be superb if everyone keeps doing it.

**Comment by ninep9up** [comment]
I will probably write a book about causality in the meantime if there's a meantime there.

**Comment by ninep9up** [comment]
It's certainly here (with me being mean and all)

**Comment by Rawi01** [comment]
@ninep9up Can you please stop spamming?

As already mentioned this feature is not part of this project. This project is an unmainntained Xposed module and the dummy backend is just for tests. You already found all the relevant details that are required to write your own backend. This is a great opportunity to learn how to write a small android app. There should be enough getting started guides online, just pick one and do it yourself if its that urgent.

**Comment by ninep9up** [comment]
Yeah, it was, once I opened it 19 days ago.

**Comment by ninep9up** [comment]
Now I feel like you're as useful as a wall after the door.

**Comment by ninep9up** [comment]
I hope your personal life is OK, just for you not to have any underlyings to act as brutal as this.

**Comment by ninep9up** [comment]
If it's not, I'm sorry.

**Comment by wish7code** [comment]
@ninep9up STOP USING DRUGS AND DRINKING IMMEDIATELY 

Say **THANKS** to @Rawi01 for all his previous efforts, contribute code or simply just shut up if **YOU** are too **LAZY** for doing the hard work on your own!

Keep in mind: your ridiculous drunkard mails reach global audience!
